---
# tasks file for selinux

- name: "Manage SELinux Packages"
  package:
    name: "{{ wtd_selinux_package_name }}"
    state: "{{ wtd_selinux_package_state }}"
  become: true
  tags:
    - "selinux"
    - "package"

- name: Manage SELinux Configuration
  selinux:
    policy: "{{ wtd_selinux_configuration_policy }}"
    state: "{{ wtd_selinux_configuration_mode }}"
  become: true
  tags:
    - "selinux"
    - "configuration"
