---
# tasks file for jetbrains

- name: "Ensure jetbrains Destination"
  file:
    path: "{{ wtd_jetbrain_toolbox_dest }}/bin"
    state: "directory"
  tags:
    - "jetbrains"
    - "toolbox"
    - "package"

- name: "Install jetbrains Toolbox"
  unarchive:
    src: "{{ wtd_jetbrains_toolbox_url }}/{{ wtd_jetbrains_toolbox_name }}"
    dest: "{{ wtd_jetbrain_toolbox_dest }}/bin/"
    creates: "{{ wtd_jetbrain_toolbox_dest }}/bin/jetbrains-toolbox"
    keep_newer: true
    remote_src: true
    mode: 0744
    extra_opts:
      - "--strip-components=1"
  tags:
    - "jetbrains"
    - "toolbox"
    - "package"
    
- name: "Create desktop Entry"
  template:
    src: "jetbrains-toolbox.desktop.j2"
    dest: "/home/{{ wtd_jetbrains_toolbox_user }}/.local/share/applications/jetbrains-toolbox.desktop"
  tags:
    - "jetbrains"
    - "toolbox"
    - "package"