---
# tasks file for update

- name: "Manage System Update"
  package:
    name: "{{ wtd_update_package_name }}"
    state: "latest"
  become: true
  tags:
    - "update"
    - "system"
    - "package"