---
# tasks file for update

- name: "Manage System Update"
  package:
    name: "{{ wtd_update_package_name }}"
    state: "latest"
  become: true
  notify:
    - "Reboot System"
  tags:
    - "update"
    - "system"
    - "package"

- name: "Flush Handlers"
  meta: "flush_handlers"
  tags:
    - "update"
    - "system"
    - "package"