---
# defaults file for gnome_desktop

## Repository Management

wtd_ws_repository_rpmfusion: "absent"

wtd_ws_flatpak_repositories:
  - name: "flathub"
    state: "present"
    url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    method: "system"

  - name: "flathub-beta"
    state: "absent"
    url: "https://flathub.org/beta-repo/flathub-beta.flatpakrepo"
    method: "system"

  - name: "fedora"
    state: "absent"
    url: "oci+https://registry.fedoraproject.org"
    method: "system"

  - name: "fedora-testing"
    state: "absent"
    url: "oci+https://registry.fedoraproject.org#testing"
    method: "system"

## Package Management

### Removals

wtd_ws_removal_packages:
  - "abrt"
  - "abrt-libs"
  - "baobab"
  - "cheese"
  - "eog"
  - "evince"
  - "file-roller"
  - "file-roller-nautilus"
  - "firefox"
  - "gedit"
  - "gnome-boxes"
  - "gnome-calculator"
  - "gnome-calendar"
  - "gnome-characters"
  - "gnome-clocks"
  - "gnome-color-viewer"
  - "gnome-contacts"
  - "gnome-font-viewer"
  - "gnome-logs"
  - "gnome-maps"
  - "gnome-photos"
  - "gnome-terminal"
  - "gnome-terminal-nautilus"
  - "gnome-weather"
  - "libreoffice-calc"
  - "libreoffice-impress"
  - "libreoffice-writer"
  - "rhythmbox"
  - "totem"

wtd_ws_removal_flatpaks: []

### Cloud

wtd_ws_cloud_packages: ""

wtd_ws_cloud_flatpaks:
  - "org.mozilla.firefox"
  - "com.nextcloud"
  # - "com.dropbox.Client"
  # - "org.sparkleshare.SparkleShare"
  # - "io.github.liberodark.OpenDrive" # google drive
  
### Communication

wtd_ws_communication_packages: []

wtd_ws_communication_flatpaks:
  - "org.gabmus.giara" # reddit
  - "org.gabmus.gfeeds" # RSS
  - "org.gnome.Polari" # IRC
  - "uk.co.ibboard.cawbird" # twitter
  # - "com.discordapp.Discord"
  # - "com.github.bleakgrey.tootle" # mastodon
  # - "com.mattermost.Desktop"
  # - "com.skype.Client"
  # - "com.teamspeak.TeamSpeak"
  # - "info.mumble.Mumble"
  # - "org.jitsi.jitsi-meet"
  # - "org.telegram.desktop"

### Development

wtd_ws_development_packages: []

wtd_ws_development_flatpaks:
  - "com.vscodium.codium" # code editor
  - "io.atom.Atom" # code editor
  - "net.bartkessels.getit" # api tool
  # - "org.gnome.gitg" # git gtk tool
  # - "org.small_tech.Gnomit" # commit message editor
  # - "uk.co.mrbenshef.Boop-GTK" # hash / crypt calculator

### Games

wtd_ws_gaming_packages: []

wtd_ws_gaming_gnome_flatpaks:
  - "org.gnome.Aisleriot" # card game
  - "org.gnome.Chess" # chess
  - "org.gnome.Games" # emulator and library
  - "org.gnome.Klotski" # push blicks around
  - "org.gnome.Mahjongg"
  - "org.gnome.Mines"
  - "org.gnome.Sudoku" # Sudoku
  - "org.gnome.SwellFoop" # kinda Tetris
  - "org.gnome.TwentyFortyEight" # 2048
  - "org.gnome.Quadrapassel" # Testris
#  - "com.albiononline.AlbionOnline" # MMORPG
#  - "com.github.Anuken.Mindustry" # Tower Defence

wtd_ws_gaming_extra_flatpaks:
  - "com.shatteredpixel.shatteredpixeldungeon" # rogue like
  - "org.hedgewars.Hedgewars" # worms-like, turn based
  # - "com.mojang.Minecraft" # minecraft
  # - "com.play0ad.zeroad" # strategy game

wtd_ws_gaming_store_flatpaks:
  - "io.github.sharkwouter.Minigalaxy" # GOG Client
  - "com.valvesoftware.Steam"

### Multimedia

wtd_ws_multimedia_packages: []

wtd_ws_multimedia_flatpaks:
  - "de.haeckerfelix.Shortwave" # internet radio
  - "org.gimp.GIMP" # graphic editor
  - "org.gnome.Lollypop" # music
  - "org.gnome.Shotwell" # picture manager
  - "org.gnome.Totem" # video player
  # - "com.belmoussaoui.Obfuscate"
  # - "com.github.maoschanz.drawing"
  # - "com.github.taiko2k.avvie"
  # - "com.github.unrud.VideoDownloader"
  # - "org.gnome.Podcasts"
  # - "org.gnome.gitlab.YaLTeR.Identity"
  # - "org.gnome.gitlab.YaLTeR.VideoTrimmer"

### Productivity

# Taste: [private|enterprise]
wtd_ws_productivity_taste: "private"

wtd_ws_productivity_private_packages: []

wtd_ws_productivity_private_flatpaks:
  - "com.jgraph.drawio.desktop" # diagrams tool
  - "org.gnome.Calculator"
  - "org.gnome.Calendar"
  - "org.gnome.Contacts"
  - "org.gnome.Documents"
  - "org.gnome.Geary"
  - "org.gnome.Notes"
  - "org.gnome.Todo"
  - "org.libreoffice.LibreOffice"

wtd_ws_productivity_enterprise_packages: []

wtd_ws_productivity_enterprise_flatpaks:
  - "com.microsoft.Teams"
  - "com.jgraph.drawio.desktop"
  - "org.gnome.Calculator"
  - "org.gnome.Documents"
  - "org.gnome.Evolution"
  - "org.libreoffice.LibreOffice"

### Security

wtd_ws_security_packages: []

wtd_ws_security_flatpaks:
  - "org.gnome.PasswordSafe" # keepass client
  # - "org.gnome.seahorse.Application" # gnome keyring manager

### System

wtd_ws_system_packages:
  - "solaar" # logitech unify manager
  - "libratbag-ratbagd" # backend for piper (see below)

wtd_ws_system_flatpaks:
  - "com.github.tchx84.Flatseal"
  - "org.freedesktop.Piper" # logitech mouse manager
  # - "com.leinardi.gst" # gtk stress testing
  # - "org.gnome.baobab" # disk usage analyzer

### Utilities

wtd_ws_utilities_packages:
  - "tilix" # terminal
  - "tilix-nautilus" # integration for nautilus

wtd_ws_utilities_flatpaks:
  - "org.gabmus.notorious" # notes with keyboard
  - "com.github.amikha1lov.RecApp" # screen recorder
  - "com.github.gi_lom.dialect" # google translate
  - "com.github.fabiocolacio.marker" # markdown editor
  - "com.github.junrrein.PDFSlicer" # pdf slice/merge
  - "com.rafaelmardojai.Blanket" # ambient noise
  - "de.haeckerfelix.Fragments" # torrent
  - "org.gnome.Characters" # character map
  - "org.gnome.Cheese" # webcam
  - "org.gnome.ColorViewer" # color profile viewer
  - "org.gnome.DejaDup" # backup
  - "org.gnome.Evince" # pdf/document viewer
  - "org.gnome.Extensions" # manage extensions
  - "org.gnome.FileRoller" # zip/tar/etc
  - "org.gnome.Maps"
  - "org.gnome.SoundRecorder"
  - "org.gnome.Weather"
  - "org.gnome.clocks"
  - "org.gnome.eog" # image preview
  - "org.gnome.gedit" # editor
  - "org.gustavoperedo.FontDownloader"
  # - "org.cvfosammmm.Setzer" # latex
  # - "org.gabmus.whatip" # internal / external ip tool
  # - "org.gnome.Logs" # journalctl for gnome
  # - "org.gnome.Firmware"
  # - "org.gnome.FontManager"
