---
# display

- name: "Nightlight"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
    state: "present"
  tags:
    - "gnome"
    - "dconf"
    - "display"
    - "configuration"

- name: "Nightlight Auto Schedule"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
    value: "true"
    state: "present"
  tags:
    - "gnome"
    - "dconf"
    - "display"
    - "configuration"