---
# tasks file for gnome_desktop

- name: "Manage dependencies"
  package:
    name: "python-psutil"
    state: "present"
  become: true
  tags:
    - "gnome"
    - "package"
    - "dependency"

- name: "Include shell tasks"
  include_tasks: "shell.yml"
  tags:
    - "gnome"
    - "shell"
    - "package"

- name: "Include desktop tasks"
  include_tasks: "desktop.yml"
  tags:
    - "gnome"
    - "desktop"
    - "configuration"
    
- name: "Include display tasks"
  include_tasks: "display.yml"
  tags:
    - "gnome"
    - "display"
    - "configuration"
    
- name: "Include keybinding tasks"
  include_tasks: "keybinding.yml"
  tags:
    - "gnome"
    - "keybinding"
    - "configuration"

- name: "Include peripherals tasks"
  include_tasks: "peripherals.yml"
  tags:
    - "gnome"
    - "peripherals"
    - "configuration"

- name: "Include privacy tasks"
  include_tasks: "privacy.yml"
  tags:
    - "gnome"
    - "privacy"
    - "configuration"