# privacy

- name: "Remove old Temp Files"
  dconf:
    key: "/org/gnome/desktop/privacy/remove-old-temp-files"
    value: "true"
    state: "present"
  tags:
    - "gnome"
    - "dconf"
    - "privacy"
    - "configuration"

- name: "Remove old Trash Files"
  dconf:
    key: "/org/gnome/desktop/privacy/remove-old-trash-files"
    value: "true"
    state: "present"
  tags:
    - "gnome"
    - "dconf"
    - "privacy"
    - "configuration"
