- name: "Manage gaming Packages"
  package:
    name: "{{ wtd_ws_gaming_packages }}"
    state: "present"
  become: true
  when:
    - "wtd_ws_gaming_packages"
  tags:
    - "gaming"
    - "package"

- name: "Manage gaming gnome Flatpaks"
  flatpak:
    name: "{{ item }}"
    state: "present"
  become: true
  loop: "{{ wtd_ws_gaming_gnome_flatpaks }}"
  when:
    - "wtd_ws_gaming_gnome_flatpaks"
  tags:
    - "gaming"
    - "flatpak"

- name: "Manage gaming extra Flatpaks"
  flatpak:
    name: "{{ item }}"
    state: "present"
  become: true
  loop: "{{ wtd_ws_gaming_extra_flatpaks }}"
  when:
    - "wtd_ws_gaming_extra_flatpaks"
  tags:
    - "gaming"
    - "flatpak"

- name: "Manage gaming store Flatpaks"
  flatpak:
    name: "{{ item }}"
    state: "present"
  become: true
  loop: "{{ wtd_ws_gaming_store_flatpaks }}"
  when:
    - "wtd_ws_gaming_store_flatpaks"
  tags:
    - "gaming"
    - "flatpak"